deploy:
  services:
    - name: youtube-processor
      # Set to the commit hash of the Docker image to deploy
      dockerCommand: 'docker run --rm -p 8080:8080 --name youtube-processor --env-file .env --network main --label com.render.service-name=youtube-processor --label com.render.project-id=f61740e3-2345-469f-9f7b-604a87277d7e --volume /tmp:/tmp --user=root --user=root --user=root ghcr.io/render-examples/youtube-processor:f61740e3-2345-469f-9f7b-604a87277d7e'
      health:
        headers:
          User-Agent: Render-Healthcheck
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
      instanceType: 'free'
      disk:
        name: youtube-processor-disk
        mountPath: /tmp
        sizeGB: 0.5
      envVars:
        - key: NODE_ENV
          value: production
        - key: DATABASE_URL
          sync: false
        - key: AWS_ACCESS_KEY_ID
          sync: false
        - key: AWS_SECRET_ACCESS_KEY
          sync: false
        - key: AWS_REGION
          sync: false
        - key: AWS_BUCKET_NAME
          sync: false
        - key: AWS_CLOUDFRONT_DOMAIN
          sync: false
        - key: REDIS_URL
          sync: false
        - key: STRIPE_SECRET_KEY
          sync: false